discord:
  bot_token: test_bot_token
  guild_id: 123456789012345678
  private_file_channel:
    - '114514'
    - '1919810'
  delete_messages_on_remove: false
dcfs:
  users:
    test_user:
      password: test_password
      readonly: false
  download:
    chunk_size_kb: 512
    download_max_concurrent_parts: 3
  jwt:
    secret: test_jwt_secret
    algorithm: HS256
    life: 3600
  metadata:
    '114514':
      name: test-notes-1
      type: pinned_message
    '1919810':
      name: test-notes-2
      type: github_repo
      github_repo:
          repo: test_user/test_repo
          commit: branch
          access_token: test_github_access_token
  server:
    host: localhost
    port: 8080
  ftp:
    enabled: true
    host: localhost
    port: 2121
