name: docker-build-push

on:
  workflow_run:
    workflows: ["Test and Coverage"]
    types:
      - completed
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        include:
          - name: dcfs
            dockerfile: Dockerfile
            image_suffix: ""
          - name: dcfs-fe
            dockerfile: Dockerfile.frontend
            image_suffix: "-fe"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}${{ matrix.image_suffix }}:latest
            ghcr.io/${{ github.repository }}${{ matrix.image_suffix }}:${{ github.sha }}
